version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: technical-interview
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../src/sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d interview"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: